[package]
name = "handlers"
version = "0.1.0"
authors = ["Samuel Sleight <samuel.sleight@gmail.com>"]
description = "A plugin for generating systems of callback handlers"
repository = "https://github.com/YeyaSwizaw/rust-handlers"
keywords = ["system", "callback", "handler", "signal", "slot"]
license = "Apache-2.0"

[lib]
plugin = true

[dependencies]
lazy_static = "^0.1.0"
